package main_test

import (
	"bytes"
	"os"
	"testing"

	extractor "github.com/xshkut/go-comments-extractor"
)

func Test_commentsExtractor_ExtractComments(t *testing.T) {
	g := extractor.NewCommentsExtractor(
		extractor.CommentsExtractorConfig{
			InputPath:           "testdata/pkg",
			OutputPath:          "testdata/schema.sql",
			InputCommentPattern: "SQL",
			OutputCommentPrefix: "--",
			OutputFileHeader:    "-- Code generated by github.com/xshkut/go-comments-extractor, DO NOT EDIT.",
		},
	)

	err := g.ExtractComments()
	if err != nil {
		t.Error(err)
		t.FailNow()
	}

	equal, err := compareFiles("testdata/expected_schema.sql", "testdata/schema.sql")
	if err != nil {
		t.Error(err)
		t.FailNow()
	}

	if !equal {
		t.Error("Files are not equal")
	}

	err = os.Remove("testdata/schema.sql")
	if err != nil {
		t.Fatal(err)
	}
}

func compareFiles(file1, file2 string) (bool, error) {
	f1, err := os.ReadFile(file1)
	if err != nil {
		return false, err
	}

	f2, err := os.ReadFile(file2)
	if err != nil {
		return false, err
	}

	return bytes.Equal(f1, f2), nil
}
