package main

// SQL: CREATE TYPE file_source AS ENUM ('aws_s3', 'google_slides', 'text');

/* SQL:
CREATE TABLE file (
    id SERIAL PRIMARY KEY,
    source file_source NOT NULL,
    key TEXT NOT NULL,
    created_by INTEGER NOT NULL REFERENCES user(id),
    created_at TIMESTAMP NOT NULL DEFAULT NOW()
);
*/

// All code below was generated by AI using the content above.

// FileSource represents the file source enum.
type FileSource string

const (
	FileSourceAwsS3        FileSource = "aws_s3"
	FileSourceGoogleSlides FileSource = "google_slides"
	FileSourceText         FileSource = "text"
)

// File represents the file entity.
type File struct {
	ID        int        `json:"id"`
	Source    FileSource `json:"source"`
	Key       string     `json:"key"`
	CreatedBy int        `json:"created_by"`
	CreatedAt string     `json:"created_at"`
}
