package pkg

/* SQL:
CREATE TABLE task (
    id SERIAL PRIMARY KEY,
    title TEXT NOT NULL, -- unique
    description TEXT NOT NULL,
    age_min INTEGER NOT NULL DEFAULT 0,
    age_max INTEGER NOT NULL DEFAULT 100,
    duration_sec INTEGER NOT NULL,
    created_by INTEGER NOT NULL REFERENCES user(id),
    created_at TIMESTAMP NOT NULL DEFAULT NOW()
);
*/

// All code below was generated by AI using the content above.

// Task represents the task entity.
type Task struct {
	ID int `json:"id"`
	// SQL: CREATE UNIQUE INDEX idx_task_title ON task (title);
	Title       string `json:"title"`
	Description string `json:"description"`
	AgeMin      int    `json:"age_min"`
	AgeMax      int    `json:"age_max"`
	DurationSec int    `json:"duration_sec"`
	CreatedBy   int    `json:"created_by"`
	CreatedAt   string `json:"created_at"`
}
